apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.component.name }}
  namespace: {{ .Values.component.namespace }}
  labels:
    name: {{ .Values.component.name }}
    project: {{ .Values.component.namespace }}
    environment: {{ .Values.component.environment }}
    tier: backend
data:
  CART_HOST: {{ .Values.endpoints.CART_HOST}}
  CART_PORT: "8080"
  USER_HOST: {{ .Values.endpoints.USER_HOST}}
  USER_PORT: "8080"
  AMQP_HOST: {{ .Values.endpoints.AMQP_HOST }}
  AMQP_USER: {{ .Values.endpoints.AMQP_USER }}
  AMQP_PASS: {{ .Values.endpoints.AMQP_PASS }}
  