apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.component.name }}
  namespace: {{ .Values.component.namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.component.replicas }}

  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      annotations:
        checksum/config: {{ include "backend.configChecksum" . | sha256sum }} ## configmap chanegs trigger deployemnt since teplate changes with diff hash value 

      labels:
        {{- include "backend.labels" . | nindent 8 }}

    spec:
      containers:
        - name: {{ .Values.component.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ .Values.component.name }}

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ports.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ports.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
            ## startup probe for not killing container on slow apps ,before liveness hits pod
          startupProbe:  
            httpGet:
              path: /health
              port: {{ .Values.ports.containerPort }}
            failureThreshold: 30
            periodSeconds: 10

          ports:
            - containerPort: {{ .Values.ports.containerPort }}

          envFrom:
            - configMapRef:
                name: {{ .Values.component.name }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          
          spec:
  containers:
  - name: cart
    image: ...

  
          