apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.component.name }}
  namespace: {{ .Values.component.namespace }}
  labels:
    name: {{ .Values.component.name }}
    project: {{ .Values.component.namespace }}
    environment: {{ .Values.component.environment }}
    tier: backend
data:
  CART_ENDPOINT: {{ .Values.endpoints.CART_ENDPOINT | quote }}
  DB_HOST: {{ .Values.endpoints.DB_HOST | quote }}
  