apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component.name }}
  namespace: {{ .Values.component.namespace }}
  labels:
    name: {{ .Values.component.name }}
    project: {{ .Values.component.namespace }}
    environment: {{ .Values.component.environment }}
    tier: backend
spec:
  type: LoadBalancer
  selector:
    name: {{ .Values.component.name }}
    project: {{ .Values.component.namespace }}
    environment: {{ .Values.component.environment }}
    tier: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.ports.servicePort }}
      targetPort: {{ .Values.ports.containerPort }}
