component :
  name : payment
  environment: dev
  namespace: roboshop
  replicas: 1

image:
  repository: "854481201869.dkr.ecr.us-east-1.amazonaws.com/stackly/payment"
  tag: "1.0.0"

endpoints:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
  AMQP_USER: "roboshop"
  AMQP_PASS: "roboshop123"
###### PORTS #######
ports :
  containerPort: 8080
  servicePort: 8080
  
  


### Resource limits and requests for the catalogue component#####
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

  