component :
  name : user
  environment: dev
  namespace: roboshop
  replicas: 1

image:
  repository: "854481201869.dkr.ecr.us-east-1.amazonaws.com/stackly/user"
  tag: "1.0.0"

endpoints:
  MONGO: "true" 
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/users"
  


### Resource limits and requests for the catalogue component#####
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

  ###### PORTS #######
  ports :
   containerPort: 8080
   servicePort: 8080
   